# vim:ft=ansible:

---
- hosts: all
  gather_facts: no
  tasks:
  - name: Wait 5 minutes
    wait_for_connection:
      sleep: 5
      timeout: 300
  
  - name: gather_facts
    setup:

  - name: Update apt cache
    package:
      update_cache: yes

  - name: Disable services
    service:
      name: unattended-upgrades
      state:   stopped
      enabled: no

- hosts: bastion
  tasks:
  - name: Install MongoDB client
    apt:
      state: present
      name:
      - mongodb-clients

  - name: Install Midnight Commander
    package:
      state: present
      name:
      - mc

- hosts: mongodb
  tasks:
  - name: Wait 5 minutes
    wait_for_connection:
      sleep: 5
      timeout: 300

  - name: Install packages required by MongoDB
    apt:
      state: present
      name:
      - mongodb-server

