# vim:ft=ansible:

- name: Install MongoDB client
  ansible.builtin.package:
    state: present
    name:
      - mongodb-clients

- name: Install Midnight Commander
  ansible.builtin.package:
    state: present
    name:
      - mc

- name: Set /etc/motd with Role name
  ansible.builtin.copy:
    src: motd
    dest: /etc/motd
    mode: 0644
